apiVersion: v2
description: A local development environment for JSON Streams
home: https://github.com/wdonne/json-streams-dev
keywords:
  - json-streams
  - development
maintainers:
  - name: Werner Donné
    email: werner.donne@pincette.net
    url: https://github.com/wdonne
name: json-streams-dev
sources:
  - https://github.com/wdonne/json-streams-dev
version: 1.0.3
