apiVersion: v1
kind: ConfigMap
metadata:
  name: sse
  namespace: {{ include "prefix" . }}sse
data:
  application.conf: |
    logLevel = "INFO"
    topic = "reply"

    {{- if .Values.sse.extraConfig }}
    include "/conf/extra.conf"
    {{- end }}

    kafka {
      bootstrap.servers = "kafka.{{ include "prefix" . }}kafka:9092"
      client.id = "sse"
    }
