apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: {{ include "prefix" . }}mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
    spec:
      containers:
        - name: mongo
          image: "mongodb/mongodb-community-server:{{ .Values.mongo.version }}-ubi9-slim"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data
              name: data
      serviceAccountName: mongo
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
