apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ include "prefix" . }}mongo
spec:
  selector:
    app.kubernetes.io/name: mongo
  ports:
    - port: 27017
      name: broker
      targetPort: 27017
      protocol: TCP
