apiVersion: v1
kind: Service
metadata:
  name: external
  namespace: {{ include "prefix" . }}kafka
spec:
  selector:
    app.kubernetes.io/name: kafka
  type: NodePort
  ports:
    - name: external
      targetPort: external
      nodePort: 30092
      protocol: TCP
      port: 9094
