apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-config
  namespace: {{ include "prefix" . }}kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
