apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-logs
  namespace: {{ include "prefix" . }}kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kafka.storage }}
