{{- if .Values.enableValidating }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Chart.Name }}.pincette.net
  {{- if and .Values.cert.ca.namespace .Values.cert.ca.name }}
  annotations:
    cert-manager.io/inject-ca-from-secret: {{ .Values.cert.ca.namespace }}/{{ .Values.cert.ca.name }}
  {{- end }}
webhooks:
  - name: {{ .Chart.Name }}.pincette.net
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
        {{- if .Values.additionalValidatingNamespaceSelectorMatchExpressions }}
        {{ toYaml .Values.additionalValidatingNamespaceSelectorMatchExpressions | nindent 8 }}
        {{- end }}
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - {{ .Chart.Name }}
        {{- if .Values.additionalValidatingObjectSelectorMatchExpressions }}
        {{ toYaml .Values.additionalValidatingObjectSelectorMatchExpressions | nindent 8 }}
        {{- end }}
    rules: {{ toYaml .Values.validatingRules | nindent 6 }}
    {{- if .Values.additionalValidatingRules }}
    {{ toYaml .Values.additionalValidatingRules | nindent 6 }}
    {{- end }}
    clientConfig:
      service:
        namespace: {{ .Chart.Name }}
        name: {{ .Chart.Name }}
        path: /validate
    admissionReviewVersions:
      - v1
    {{- if .Values.validatingFailurePolicy }}
    failurePolicy: {{ .Values.validatingFailurePolicy }}
    {{- end }}
    sideEffects: None
    timeoutSeconds: 5
  {{- end }}
