apiVersion: v1
kind: ConfigMap
metadata:
  name: jes-http
  namespace: {{ include "prefix" . }}jes-http
data:
  application.conf: |
    {{- if .Values.jeshttp.extraConfig }}
    include "/conf/extra.conf"
    {{- end }}

    logLevel = "INFO"
    accessLog = true
    slowRequestThreshold = "0.1s"

    kafka {
      bootstrap.servers = "kafka.{{ include "prefix" . }}kafka:9092"
      client.id = "jes-http"
    }

    mongodb {
      database = "local"
      uri = "mongodb://mongo.{{ include "prefix" . }}mongo:27017"
    }
