apiVersion: apps/v1
kind: Deployment
metadata:
  name: jes-http
  namespace: {{ include "prefix" . }}jes-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jes-http
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jes-http
    spec:
      containers:
        - name: jes-http
          image: "jsoneventsourcing/pincette-jes-http:{{ .Values.jeshttp.version }}"
          imagePullPolicy: IfNotPresent
          command:
            - java
          args:
            - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
            - -Dconfig.file=/conf/application.conf
            - -cp
            - "@/app/jib-classpath-file"
            - net.pincette.jes.http.ApiServer
            - "9000"
          ports:
            - name: http
              containerPort: 9000
          volumeMounts:
            - name: config
              mountPath: /conf/application.conf
              subPath: application.conf
          {{- if .Values.jeshttp.extraConfig }}
            - name: extra
              mountPath: /conf/extra.conf
              subPath: extra.conf
          {{- end }}
      serviceAccountName: jes-http
      volumes:
        - name: config
          configMap:
            name: jes-http
      {{- if .Values.jeshttp.extraConfig }}
        - name: extra
          configMap:
            name: extra
      {{- end }}
