apiVersion: v1
kind: Service
metadata:
  name: jes-http
  namespace: {{ include "prefix" . }}jes-http
spec:
  selector:
    app.kubernetes.io/name: jes-http
  type: NodePort
  ports:
    - name: http
      port: 9000
      nodePort: 30020
      targetPort: http
      protocol: TCP
