apiVersion: v1
kind: Service
metadata:
  name: letter-box
  namespace: {{ include "prefix" . }}letter-box
spec:
  selector:
    app.kubernetes.io/name: letter-box
  type: NodePort
  ports:
    - name: http
      port: 9000
      nodePort: 30022
      targetPort: http
      protocol: TCP
